### ISSUE TITLE
Clean up output message

### ISSUE THREAD

**Issue by jendoebelin** [astrobleem/Simple-StableLM-Chat#8]
As the user, I do not want my question to be repeated in the output, I just want to see the answer.

![Image](https://user-images.githubusercontent.com/119360121/233812711-71da7434-ece0-434a-84aa-0405cc78240c.png)

**Comment by jendoebelin** [comment]
Ok I'll assign it to Jen.

**Comment by astrobleem** [comment]
thanks for completing this task, jen!

**Comment by astrobleem** [comment]
![image](https://user-images.githubusercontent.com/7433842/234352029-5f0cbfc7-573e-42b3-9dcc-3ed5b6d111dc.png)
