### ISSUE TITLE
Convert seconds to minutes

### ISSUE THREAD

**Issue by jendoebelin** [astrobleem/Simple-StableLM-Chat#9]
As a user, it is easier to see time elapsed in minutes rather than seconds.

![Image](https://user-images.githubusercontent.com/119360121/233812820-23a99ae0-44a5-40fc-9721-dfa1ee5a00a0.png)

**Comment by astrobleem** [comment]
![image](https://user-images.githubusercontent.com/7433842/234352116-1941c862-05d5-4c5a-b145-cdfc1d7ffb80.png)

do a git pull
